---
- name: Setup GitHub Runner
  hosts: gitlab-runners
  become: true

  tasks:
    - name: Create {{ runner_workdir }}
      file:
        path: "{{ runner_workdir }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: 0757

    - name: Download and extract GitHub Actions Runner
      become: false
      ansible.builtin.unarchive:
        src: https://github.com/actions/runner/releases/download/v2.312.0/actions-runner-linux-x64-2.312.0.tar.gz
        dest: "{{ runner_workdir }}"
        remote_src: true

    - name: Remove runner config (for idempotency)
      become: false
      command: "{{ runner_workdir }}/config.sh remove --token {{ access_token }}"
      ignore_errors: true
      when: force | default(false) | bool

    - name: Configure GitHub Actions Runner
      become: false
      command: |
        ./config.sh --url "{{ github_repo_url }}" \
        --token "{{ access_token }}" \
        --name {{ runner_name }} \
        --labels {{ runner_labels }} \
        --work {{ runner_workdir }} \
        --unattended
      args:
        chdir: "{{ runner_workdir }}"

    - name: Create systemd unit file for GitHub Runner
      ansible.builtin.template:
        src: github-runner.service.j2
        dest: /etc/systemd/system/github-runner.service
      notify: Reload systemd

    - name: Start and enable the GitHub Runner service
      ansible.builtin.service:
        name: github-runner
        state: started
        enabled: yes

  handlers:
    - name: Reload systemd
      ansible.builtin.systemd:
        name: github-runner
        state: restarted
